openapi: 3.0.0
info:
  title: Movie Recommendation System - Admin API
  description: API documentation for admin operations in the Movie Recommendation System
  version: 1.0.0
  contact:
    email: admin@movierec.com

servers:
  - url: http://localhost:3000/api/v1
    description: Development server
  - url: https://api.movierec.com/v1
    description: Production server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        status:
          type: boolean
          default: false
        statusCode:
          type: integer
        message:
          type: string

    Review:
      type: object
      properties:
        _id:
          type: string
        content:
          type: string
        rating:
          type: number
        status:
          type: string
          enum: [pending, approved, rejected, removed]
        user:
          type: object
          properties:
            _id:
              type: string
            username:
              type: string
            email:
              type: string
        movie:
          type: object
          properties:
            _id:
              type: string
            title:
              type: string
            releaseDate:
              type: string
              format: date
        reports:
          type: array
          items:
            type: object
            properties:
              reason:
                type: string
              reportedBy:
                type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    MovieStats:
      type: object
      properties:
        mostViewed:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              movie:
                type: object
                properties:
                  title:
                    type: string
                  releaseDate:
                    type: string
                    format: date
              totalViews:
                type: number
        recentlyAdded:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              title:
                type: string
              releaseDate:
                type: string
                format: date

    UserStats:
      type: object
      properties:
        newUsers:
          type: number
        activeUsers:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              user:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
              activityCount:
                type: number

    GenreStats:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
          views:
            type: number

    ActorStats:
      type: array
      items:
        type: object
        properties:
          _id:
            type: string
          actor:
            type: object
            properties:
              name:
                type: string
              imageUrl:
                type: string
          searchCount:
            type: number

    EngagementStats:
      type: object
      properties:
        reviews:
          type: object
          properties:
            totalReviews:
              type: number
            avgRating:
              type: number
        engagement:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              count:
                type: number

    SiteStatistics:
      type: object
      properties:
        movies:
          $ref: '#/components/schemas/MovieStats'
        users:
          $ref: '#/components/schemas/UserStats'
        genres:
          $ref: '#/components/schemas/GenreStats'
        actors:
          $ref: '#/components/schemas/ActorStats'
        engagement:
          $ref: '#/components/schemas/EngagementStats'

paths:
  /api/v1/admin/moderation:
    get:
      summary: Get movie and review moderation data
      description: Retrieves pending and reported reviews for moderation
      security:
        - BearerAuth: []
      tags:
        - Moderation
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    default: true
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      pendingReviews:
                        type: array
                        items:
                          $ref: '#/components/schemas/Review'
                      reportedReviews:
                        type: array
                        items:
                          $ref: '#/components/schemas/Review'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Not an admin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/admin/moderation/review/{reviewId}:
    patch:
      summary: Moderate a review
      description: Approve, reject, or remove a review
      security:
        - BearerAuth: []
      tags:
        - Moderation
      parameters:
        - in: path
          name: reviewId
          required: true
          schema:
            type: string
          description: ID of the review to moderate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - action
              properties:
                action:
                  type: string
                  enum: [approve, reject, remove]
                reason:
                  type: string
                  description: Required when action is reject or remove
      responses:
        '200':
          description: Review moderated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    default: true
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/Review'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Review not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/admin/statistics:
    get:
      summary: Get site statistics
      description: Retrieve comprehensive site statistics and analytics
      security:
        - BearerAuth: []
      tags:
        - Statistics
      parameters:
        - in: query
          name: timeframe
          schema:
            type: string
            enum: [24h, 7d, 30d, all]
            default: 7d
          description: Time period for statistics
      responses:
        '200':
          description: Statistics retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    default: true
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/SiteStatistics'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden - Not an admin
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

tags:
  - name: Moderation
    description: Movie and review moderation endpoints
  - name: Statistics
    description: Site statistics and analytics endpoints

security:
  - BearerAuth: []