openapi: 3.0.0
info:
  title: Awards API
  version: 1.0.0
  description: API endpoints for movie awards management

paths:
  /api/v1/awards:
    post:
      tags:
        - Awards
      summary: Create a new award
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AwardInput'
            examples:
              award:
                summary: Example award submission
                value:
                  name: "Academy Award"
                  organization: "Academy of Motion Picture Arts and Sciences"
                  category: "Best Picture"
                  year: 2024
                  ceremony: "96th Academy Awards"
                  isNomination: true
                  isWinner: false
                  movie: "65f1a234b876a123b45c6789"
                  recipients: [
                    {
                      name: "John Smith",
                      role: "Producer"
                    }
                  ]
                  description: "The Academy Award for Best Picture"
                  imageUrl: "https://example.com/image.jpg"
                  sourceUrl: "https://example.com/source"
      responses:
        201:
          description: Award created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwardResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/awards/{awardId}:
    put:
      tags:
        - Awards
      summary: Update an award
      security:
        - BearerAuth: []
      parameters:
        - name: awardId
          in: path
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AwardUpdateInput'
      responses:
        200:
          description: Award updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwardResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'
    
    delete:
      tags:
        - Awards
      summary: Delete an award
      security:
        - BearerAuth: []
      parameters:
        - name: awardId
          in: path
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
      responses:
        200:
          description: Award deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/awards/search:
    get:
      tags:
        - Awards
      summary: Search awards
      parameters:
        - name: organization
          in: query
          schema:
            type: string
            pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        - name: category
          in: query
          schema:
            type: string
            pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        - name: year
          in: query
          schema:
            type: integer
            minimum: 1900
            maximum: 2100
        - name: isWinner
          in: query
          schema:
            type: boolean
        - name: recipient
          in: query
          schema:
            type: string
            pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        - name: movie
          in: query
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        200:
          description: Awards retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwardListResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/awards/by-year:
    get:
      tags:
        - Awards
      summary: Get awards by year
      parameters:
        - name: year
          in: query
          required: true
          schema:
            type: integer
            minimum: 1900
            maximum: 2100
        - name: organization
          in: query
          schema:
            type: string
            pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
      responses:
        200:
          description: Awards retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwardListResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/awards/winners:
    get:
      tags:
        - Awards
      summary: Get award winners
      parameters:
        - name: organization
          in: query
          required: true
          schema:
            type: string
            pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        - name: year
          in: query
          required: true
          schema:
            type: integer
            minimum: 1900
            maximum: 2100
      responses:
        200:
          description: Award winners retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwardListResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        500:
          $ref: '#/components/responses/ServerError'

  /api/v1/awards/movies/{movieId}:
    get:
      tags:
        - Awards
      summary: Get awards for a movie
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{24}$'
      responses:
        200:
          description: Movie awards retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AwardListResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
        500:
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    AwardInput:
      type: object
      properties:
        name:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
          example: "Academy Award"
          description: "Award name - alphanumeric characters, spaces, and basic punctuation only"
        organization:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
          example: "Academy of Motion Picture Arts and Sciences"
          description: "Organization name - alphanumeric characters, spaces, and basic punctuation only"
        category:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
          example: "Best Picture"
          description: "Award category - alphanumeric characters, spaces, and basic punctuation only"
        year:
          type: integer
          minimum: 1900
          maximum: 2100
          example: 2024
        ceremony:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"  
          example: "96th Academy Awards"
          description: "Ceremony name - alphanumeric characters, spaces, and basic punctuation only"
        isNomination:
          type: boolean
          default: true
          example: true
        isWinner:
          type: boolean
          default: false
          example: false
        movie:
          type: string
          pattern: '^[0-9a-fA-F]{24}$'
          example: "65f1a234b876a123b45c6789"
          description: "MongoDB ObjectId of the movie"
        recipients:
          type: array
          items:
            type: object
            required:
              - name
              - role
            properties:
              name:
                type: string
                pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$" 
                example: "John Smith"
                description: "Recipient name - alphanumeric characters, spaces, and basic punctuation only"
              role:
                type: string
                pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$" 
                example: "Producer"
                description: "Recipient role - alphanumeric characters, spaces, and basic punctuation only"
          minItems: 1
        description:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$" 
          example: "The Academy Award for Best Picture"
          description: "Award description - alphanumeric characters, spaces, and basic punctuation only"
        imageUrl:
          type: string
          format: uri
          pattern: "^https?:\\/\\/.+" 
          example: "https://example.com/image.jpg"
        sourceUrl:
          type: string
          format: uri
          pattern: "^https?:\\/\\/.+" 
          example: "https://example.com/source"
      required:
        - name
        - organization
        - category
        - year
        - ceremony
        - recipients
        - movie
      additionalProperties: false

    AwardUpdateInput:
      type: object
      properties:
        name:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        organization:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        category:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        year:
          type: integer
          minimum: 1900
          maximum: 2100
        ceremony:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        isNomination:
          type: boolean
        isWinner:
          type: boolean
        recipients:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
              role:
                type: string
                pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
            required:
              - name
              - role
        description:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        imageUrl:
          type: string
          format: uri
          pattern: "^https?:\\/\\/.+"
        sourceUrl:
          type: string
          format: uri
          pattern: "^https?:\\/\\/.+"
      minProperties: 1
      additionalProperties: false

    Award:
      allOf:
        - $ref: '#/components/schemas/AwardInput'
        - type: object
          properties:
            _id:
              type: string
              pattern: '^[0-9a-fA-F]{24}$'
            movie:
              $ref: '#/components/schemas/Movie'
            createdAt:
              type: string
              format: date-time
            updatedAt:
              type: string
              format: date-time

    Movie:
      type: object
      properties:
        _id:
          type: string
          pattern: '^[0-9a-fA-F]{24}$'
        title:
          type: string
          pattern: "^[a-zA-Z0-9\\s\\-.,\"'()]+$"
        releaseDate:
          type: string
          format: date-time

    AwardResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/Award'
      required:
        - success
        - message
        - data

    AwardListResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
          properties:
            results:
              type: array
              items:
                $ref: '#/components/schemas/Award'
            total:
              type: integer
              minimum: 0
            page:
              type: integer
              minimum: 1
            totalPages:
              type: integer
              minimum: 1
          required:
            - results
            - total
            - page
            - totalPages
      required:
        - success
        - message
        - data

  responses:
    BadRequest:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: "Invalid request data"
              error:
                type: object
                properties:
                  details:
                    type: string
                    example: "Validation error in request body"

    Unauthorized:
      description: Authentication required
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: "Authentication required"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: "Resource not found"

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              message:
                type: string
                example: "Internal server error"

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT