# docs/swagger/recommendation.yaml
openapi: 3.0.0
info:
  title: Movie Recommendation API
  version: 1.0.0
  description: API endpoints for movie recommendations

paths:
  /api/v1/recommendations/movies/{movieId}/similar:
    get:
      tags:
        - Recommendations
      summary: Get similar movies
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Similar movies retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Movie'

  /api/v1/recommendations/personalized:
    get:
      tags:
        - Recommendations
      summary: Get personalized movie recommendations
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Personalized recommendations retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/Movie'
                      total:
                        type: integer
                      page:
                        type: integer
                      totalPages:
                        type: integer

  /api/v1/recommendations/trending:
    get:
      tags:
        - Recommendations
      summary: Get trending movies
      parameters:
        - name: period
          in: query
          schema:
            type: string
            enum: [daily, weekly, monthly]
            default: weekly
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Trending movies retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/Movie'
                      total:
                        type: integer
                      page:
                        type: integer
                      totalPages:
                        type: integer

  /api/v1/recommendations/top-rated:
    get:
      tags:
        - Recommendations
      summary: Get top rated movies
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Top rated movies retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      results:
                        type: array
                        items:
                          $ref: '#/components/schemas/Movie'
                      total:
                        type: integer
                      page:
                        type: integer
                      totalPages:
                        type: integer