# src/docs/swagger/users.yaml
openapi: 3.0.0
paths:
  /api/v1/users/profile:
    get:
      tags:
        - Users
      summary: Get user profile
      description: Retrieve the current user's profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
    
    put:
      tags:
        - Users
      summary: Update user profile
      description: Update the current user's profile information
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdate'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/v1/users:
    get:
      tags:
        - Users
      summary: Get all users (Admin only)
      description: Retrieve a list of all users (requires admin role)
      security:
        - BearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Number of items per page
      responses:
        '200':
          description: Users retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsersListResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'

components:
  schemas:
    ProfileUpdate:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        'profile.bio':
          type: string
          maxLength: 500
          example: "Movie enthusiast and critic"
        'profile.avatar':
          type: string
          example: "avatar-url.jpg"

    ProfileResponse:
      allOf:
        - $ref: '#/components/schemas/Success'
        - type: object
          properties:
            data:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "5f9d4a3b9d3e2a1b3c5d8e7f"
                    email:
                      type: string
                      example: "john@example.com"
                    name:
                      type: string
                      example: "John Doe"
                    role:
                      type: string
                      enum: [admin, user]
                      example: "user"
                    profile:
                      type: object
                      properties:
                        bio:
                          type: string
                          example: "Movie enthusiast and critic"
                        preferences:
                          type: object
                          properties:
                            genres:
                              type: array
                              items:
                                type: string
                              example: ["Action", "Comedy"]
                            actors:
                              type: array
                              items:
                                type: string
                              example: ["Tom Hanks"]
                            directors:
                              type: array
                              items:
                                type: string
                              example: ["Christopher Nolan"]
                        avatar:
                          type: string
                          example: "avatar-url.jpg"

    UsersListResponse:
      allOf:
        - $ref: '#/components/schemas/Success'
        - type: object
          properties:
            data:
              type: object
              properties:
                users:
                  type: array
                  items:
                    type: object
                    properties:
                      _id:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
                      role:
                        type: string
                        enum: [admin, user]
                      isActive:
                        type: boolean
                pagination:
                  type: object
                  properties:
                    total:
                      type: integer
                    pages:
                      type: integer
                    page:
                      type: integer
                    limit:
                      type: integer